# Generated by Django 4.1.2 on 2023-02-08 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Брэнды',
                'verbose_name_plural': 'Брэнды',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('photo', models.ImageField(upload_to='pictures/%y/%m/%d/', verbose_name='Фото')),
                ('alternative_photo', models.ImageField(blank=True, null=True, upload_to='alternative-pictures/%y/%m/%d/', verbose_name='Фото 2')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(choices=[('Man', 'Для мужчин'), ('Woman', 'Для женщин'), ('All', 'Унисекс')], default='All', max_length=5, verbose_name='Пол')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clothes.brand', verbose_name='Брэнд')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clothes.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Вещи',
                'verbose_name_plural': 'Вещи',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_title', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('size', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Размеры',
                'verbose_name_plural': 'Размеры',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clothes.category')),
            ],
            options={
                'verbose_name': 'Подкатегории',
                'verbose_name_plural': 'Подкатегории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sizes_of_Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('id_clothes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clothes.clothes', verbose_name='id товара')),
                ('id_size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clothes.sizes', verbose_name='id размера')),
            ],
            options={
                'verbose_name': 'Размеры вещей',
                'verbose_name_plural': 'Размеры вещей',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Принят в исполнение')),
                ('status', models.CharField(choices=[('Ok', 'Исполнено'), ('Canceled', 'Отменен'), ('In progress', 'В процессе')], default='In progress', max_length=11, verbose_name='Статус')),
                ('time_accept', models.DateTimeField(default=None, verbose_name='Принят в пункте выдачи')),
                ('count', models.IntegerField(verbose_name='Кол-во')),
                ('total_price', models.IntegerField(verbose_name='Общая стоимость')),
                ('product', models.ManyToManyField(to='clothes.sizes_of_clothes', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказы',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='clothes',
            name='sizes',
            field=models.ManyToManyField(through='clothes.Sizes_of_Clothes', to='clothes.sizes'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clothes.subcategory', verbose_name='Подкатегория'),
        ),
    ]
