# Generated by Django 4.1.2 on 2023-02-12 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user_name',
            field=models.CharField(default=None, max_length=255, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='time_accept',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 17, 38, 14, 578686), verbose_name='Принят в пункте выдачи'),
        ),
    ]
