# Generated by Django 4.1.2 on 2023-03-16 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='time_accept',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 17, 18, 16, 23, 776860, tzinfo=datetime.timezone.utc), verbose_name='Принят в пункте выдачи'),
        ),
    ]
