# Generated by Django 4.1.2 on 2023-02-14 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_orders_user_name_alter_orders_time_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='time_accept',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 15, 18, 58, 41, 382105), verbose_name='Принят в пункте выдачи'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_price',
            field=models.IntegerField(null=True, verbose_name='Общая стоимость'),
        ),
    ]
