# Generated by Django 4.1.2 on 2023-02-14 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_alter_orders_time_accept_alter_orders_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='time_accept',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 15, 19, 1, 0, 593283), verbose_name='Принят в пункте выдачи'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='Общая стоимость'),
        ),
    ]
