# Generated by Django 4.1.2 on 2023-02-14 17:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_alter_orders_time_accept_alter_orders_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='count',
        ),
        migrations.AlterField(
            model_name='orders',
            name='time_accept',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 15, 20, 39, 11, 339059), verbose_name='Принят в пункте выдачи'),
        ),
        migrations.AlterField(
            model_name='sizes_of_clothes',
            name='count',
            field=models.IntegerField(verbose_name='Кол-во'),
        ),
        migrations.CreateModel(
            name='Orders_of_Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Кол-во')),
                ('id_clothes_with_size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clothes.sizes_of_clothes', verbose_name='id товара')),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clothes.orders', verbose_name='id размера')),
            ],
            options={
                'verbose_name': 'Наполнение заказа',
                'verbose_name_plural': 'Наполнение заказа',
                'ordering': ['id'],
            },
        ),

        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.ManyToManyField(through='clothes.Orders_of_Clothes', to='clothes.sizes_of_clothes', verbose_name='Товар'),
        ),
    ]
