# Generated by Django 4.1.2 on 2023-02-15 15:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clothes', '0005_remove_orders_count_alter_orders_time_accept_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders_of_clothes',
            options={'ordering': ['id'], 'verbose_name': 'Наполнение заказов', 'verbose_name_plural': 'Наполнение заказов'},
        ),
        migrations.AlterField(
            model_name='orders',
            name='time_accept',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 18, 48, 35, 513545), verbose_name='Принят в пункте выдачи'),
        ),
        migrations.AlterField(
            model_name='orders_of_clothes',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Кол-во'),
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'О пользователях',
                'verbose_name_plural': 'О пользователях',
                'ordering': ['id'],
            },
        ),
    ]
