# Generated by Django 4.2 on 2023-04-15 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0005_alter_orders_time_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='time_accept',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 16, 8, 27, 0, 578042, tzinfo=datetime.timezone.utc), verbose_name='Принят в пункте выдачи'),
        ),
    ]
