# Generated by Django 4.1.2 on 2022-11-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0005_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothes',
            options={'ordering': ['id'], 'verbose_name': 'Вещи', 'verbose_name_plural': 'Вещи'},
        ),
        migrations.AddField(
            model_name='clothes',
            name='alternative_photo',
            field=models.ImageField(null=True, upload_to='alternative-pictures/%y/%m/%d/'),
        ),
    ]
