# Generated by Django 4.1.2 on 2023-01-24 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0006_alter_clothes_options_clothes_alternative_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='alternative_photo',
            field=models.ImageField(blank=True, null=True, upload_to='alternative-pictures/%y/%m/%d/', verbose_name='Фото 2'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clothes.brand', verbose_name='Брэнд'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clothes.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='content',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='gender',
            field=models.CharField(choices=[('Man', 'Для мужчин'), ('Woman', 'Для женщин'), ('All', 'Унисекс')], default='All', max_length=5, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='photo',
            field=models.ImageField(upload_to='pictures/%y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clothes.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
