# Generated by Django 4.1.2 on 2023-02-01 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0009_remove_sizes_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sizes_of_Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('id_clothes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clothes.clothes', verbose_name='id товара')),
                ('id_size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clothes.sizes', verbose_name='id размера')),
            ],
            options={
                'verbose_name': 'Размеры вещей',
                'verbose_name_plural': 'Размеры вещей',
                'ordering': ['id'],
            },
        ),

        migrations.RemoveField(
            model_name='clothes',
            name='sizes',
        ),
        migrations.AddField(
            model_name='clothes',
            name='sizes',
            field=models.ManyToManyField(through='clothes.Sizes_of_Clothes', to='clothes.sizes'),
        ),
    ]
