# Generated by Django 4.1.2 on 2023-02-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0010_sizes_of_clothes_alter_clothes_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Принят в исполнение')),
                ('status', models.CharField(choices=[('Ok', 'Исполнено'), ('Canceled', 'Отменен'), ('In progress', 'В процессе')], default='In progress', max_length=11, verbose_name='Статус')),
                ('time_accept', models.DateTimeField(default=None, verbose_name='Принят в пункте выдачи')),
                ('count', models.IntegerField(verbose_name='Кол-во')),
                ('total_price', models.IntegerField(verbose_name='Общая стоимость')),
                ('product', models.ManyToManyField(to='clothes.clothes', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказы',
                'ordering': ['id'],
            },
        ),
    ]
