# Generated by Django 4.1.2 on 2023-02-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0010_sizes_of_clothes_alter_clothes_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='L',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
