# Generated by Django 4.1.2 on 2023-02-07 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0011_l'),
    ]

    operations = [
        migrations.DeleteModel(
            name='L',
        ),
    ]


