# Generated by Django 4.1.2 on 2023-02-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0011_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='time_accept',
            field=models.DateTimeField(default=None, verbose_name='Принят в пункте выдачи'),
        ),
    ]
