# Generated by Django 4.1.2 on 2023-02-07 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0012_delete_l'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Принят в исполнение')),
                ('status', models.CharField(choices=[('Ok', 'Исполнено'), ('Canceled', 'Отменен'), ('In progress', 'В процессе')], default='In progress', max_length=11, verbose_name='Статус')),
                ('time_accept', models.DateTimeField(default=None, verbose_name='Принят в пункте выдачи')),
                ('count', models.IntegerField(verbose_name='Кол-во')),
                ('total_price', models.IntegerField(verbose_name='Общая стоимость')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clothes.clothes', verbose_name='Товар')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clothes.sizes', verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказы',
                'ordering': ['id'],
            },
        ),
    ]
