# Generated by Django 4.1.2 on 2023-02-07 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0013_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
